// Auto-generated by scripts/generate-celebrity-data.ts
// Last updated: 2025-12-19T22:54:18.969Z
// Do not edit manually - regenerate with: bun run scripts/generate-celebrity-data.ts

export interface CelebrityAppearance {
  file: string;
  page: number;
  confidence: number;
}

export interface Celebrity {
  name: string;
  count: number;
  appearances: CelebrityAppearance[];
}

// Mock data for UI development - will be replaced by real data after batch processing
export const CELEBRITY_DATA: Celebrity[] = [
  {
    "name": "Jeffrey Epstein",
    "count": 3,
    "appearances": [
      { "file": "VOL00002/IMAGES/0001/EFTA00003188.pdf", "page": 1, "confidence": 100.0 },
      { "file": "VOL00002/IMAGES/0001/EFTA00003296.pdf", "page": 4, "confidence": 100.0 },
      { "file": "VOL00002/IMAGES/0001/EFTA00003409.pdf", "page": 1, "confidence": 100.0 }
    ]
  },
  {
    "name": "Ghislaine Maxwell",
    "count": 3,
    "appearances": [
      { "file": "VOL00002/IMAGES/0001/EFTA00003182.pdf", "page": 1, "confidence": 100.0 },
      { "file": "VOL00002/IMAGES/0001/EFTA00003188.pdf", "page": 1, "confidence": 99.4 },
      { "file": "VOL00002/IMAGES/0001/EFTA00003296.pdf", "page": 4, "confidence": 100.0 }
    ]
  },
  {
    "name": "Benoit Mandelbrot",
    "count": 1,
    "appearances": [
      { "file": "VOL00002/IMAGES/0001/EFTA00003409.pdf", "page": 1, "confidence": 100.0 }
    ]
  },
  {
    "name": "Umar Dzhabrailov",
    "count": 1,
    "appearances": [
      { "file": "VOL00002/IMAGES/0001/EFTA00003296.pdf", "page": 1, "confidence": 99.8 }
    ]
  },
  {
    "name": "Bill Kenney",
    "count": 1,
    "appearances": [
      { "file": "VOL00002/IMAGES/0001/EFTA00003188.pdf", "page": 1, "confidence": 75.2 }
    ]
  }
];

// Helper to get files for a celebrity (filtered by confidence threshold)
export function getFilesForCelebrity(
  celebrityName: string,
  minConfidence: number = 99
): string[] {
  const celebrity = CELEBRITY_DATA.find((c) => c.name === celebrityName);
  if (!celebrity) return [];

  return celebrity.appearances
    .filter((a) => a.confidence >= minConfidence)
    .map((a) => a.file);
}

// Get celebrities filtered by minimum confidence, sorted by appearance count
export function getCelebritiesAboveConfidence(minConfidence: number = 99): Celebrity[] {
  return CELEBRITY_DATA
    .map((celebrity) => ({
      ...celebrity,
      appearances: celebrity.appearances.filter((a) => a.confidence >= minConfidence),
    }))
    .filter((celebrity) => celebrity.appearances.length > 0)
    .map((celebrity) => ({
      ...celebrity,
      count: celebrity.appearances.length,
    }))
    .sort((a, b) => b.count - a.count);
}

// Build a map of file -> celebrities for quick lookup
export function buildFileToCelebritiesMap(
  minConfidence: number = 99
): Map<string, string[]> {
  const map = new Map<string, string[]>();

  for (const celebrity of CELEBRITY_DATA) {
    for (const appearance of celebrity.appearances) {
      if (appearance.confidence >= minConfidence) {
        const existing = map.get(appearance.file) || [];
        existing.push(celebrity.name);
        map.set(appearance.file, existing);
      }
    }
  }

  return map;
}
